### ISSUE TITLE
template not parsing

### ISSUE THREAD

**Issue by Lacoi** [genkgo/xsl#12]
Hi,

my xsl file works with xsltproc. But with your lib it doesn't parse the following part:

**XML**

```
<ItemTypes>
    <Item id="test">
        <Requirement id="subtest" min="10"/>
    </Item>
</ItemTypes>

```

**XSL**
`<xsl:apply-templates select="Requirement[name(id(@id))='Item']" mode="min"/>`

```
<xsl:template match="Requirement|EffectReq" mode="min"><xsl:value-of select="count(id(@id)/preceding-sibling::*)"/> => <xsl:value-of select="@min"/><xsl:if test="position()!=last()">, </xsl:if>
</xsl:template>
```

Have you any idea?

**Comment by frederikbosch** [comment]
@dunger Are you sure it is related to this library? I just [pushed a test](https://github.com/genkgo/xsl/commit/b832d1331e0591050ef087dd1f6de80ae9521fa7) that proves that this library is behaving the same as libxslt. Or is my test wrong?

**Comment by Lacoi** [comment]
i don't know much about xsl. The xsl and xml file were created by other persons.
With your test file i get the result and following xml:

```
<ItemTypes>
    <Item id="test">
        <Requirement id="subtest" min="10"/>
        <Requirement id="subtest2" min="20"/>
        <Requirement id="subtest3" min="30"/>
        <Requirement id="subtest4" min="40"/>
    </Item>
</ItemTypes>
```

Result
`0 => 10, 0 => 20, 0 => 30, 0 => 40`

expected result:
`subtest => 10, subtest2 => 20, subtest3 => 30, subtest4 => 40`

i don't know if i'm doing something wrong

**Comment by frederikbosch** [comment]
@dunger That is not the expected result.

``` xpath
count(id(@id)/preceding-sibling::*)
```

This returns a count. So if we would expect something, it would be an integer, not a string. If I change the stylesheet to this.

``` xsl
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template match="/">
        <xsl:apply-templates select=".//Requirement" mode="min"/>
    </xsl:template>

    <xsl:template match="Requirement|EffectReq" mode="min">
        <xsl:value-of select="@id"/> => <xsl:value-of select="@min"/><xsl:if test="position()!=last()">, </xsl:if>
    </xsl:template>

</xsl:stylesheet>
```

Then I am expecting a string because `@id` returns a string.

**Comment by frederikbosch** [comment]
By the way, if you are using this library: you can use XSL 2.0 (that is the purpose of this library). Then you can do this.

``` xsl
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template match="/">
        <xsl:apply-templates select=".//Requirement" mode="min"/>
    </xsl:template>

    <xsl:template match="Requirement|EffectReq" mode="min">
        <xsl:value-of select="concat(@id, ' => ', @min)" separator=","/>
    </xsl:template>

</xsl:stylesheet>
```

**Comment by Lacoi** [comment]
Sry. i think it was my bad. I made some mistakes.
XSL: https://github.com/Uga-Agga/Game/blob/master/src/config/config.php.xsl
DTD: https://github.com/Uga-Agga/Game/blob/master/src/config/config.php.xsl

XML header:

```
<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE Config SYSTEM "config.dtd">
<Config>
....
```

is the config.dtd parsed/included?

**Comment by frederikbosch** [comment]
@dunger My library is not doing anything with it. So it depends if [the native PHP extension](http://php.net/manual/en/book.xsl.php) is parsing/including it.

**Comment by Lacoi** [comment]
Ok, thank you for your help. It was my bad.

**Comment by frederikbosch** [comment]
No problem, hope the package is useful.
