### ISSUE TITLE
Catchable fatal error

### ISSUE THREAD

**Issue by ossantr** [genkgo/xsl#13]
Hi,

I tried to use genkgo to perform an xsl transformation on an xml, but I have this error : 

Catchable fatal error: Argument 1 passed to Genkgo\Xsl\Xsl\Functions\CurrentGroup::isForEachGroupElement() must be an instance of DOMNode, null given, called in C:\wamp64\www\portail\V1\php\vendor\genkgo\xsl\src\Xsl\Functions\CurrentGroup.php on line 40 and defined in C:\wamp64\www\portail\V1\php\vendor\genkgo\xsl\src\Xsl\Functions\CurrentGroup.php on line 69

Do you know how to deal with it ?

`<?php`
`require __DIR__ . '/vendor/autoload.php'; `
`use Genkgo\Xsl\XsltProcessor;`
`//XML`
`$xml_doc = new DOMDocument();`
`$xml_doc->load("../php/recupFile.xml");`
`// XSL`
`$xsl_doc = new DOMDocument();`
`$xsl_doc->load("../xslt/filtre_xml_tei.xsl");`
`// Proc`
`$proc = new XSLTProcessor();`
`$proc->importStylesheet($xsl_doc)`		
`$proc->transformToDoc($xml_doc);`
`?>`

The xsl and xsml files are pretty long but I can show it to you if you want. Sorry if the solution is obvious, it's the first time I use a php library. Thank you in advance.

**Comment by frederikbosch** [comment]
Would love to help you, but I need at least a (partial) XML and XSL file to have an idea how to fix the problem.

**Comment by ossantr** [comment]
Thank you for your answer.

Because I can't attach them with their original formats I made it with the .txt format, hope it's ok for you, the first one is the .xml file and the second one is the .xsl file.
 
[recupFile.txt](https://github.com/genkgo/xsl/files/1625543/recupFile.txt)
[filtre_xml_tei.txt](https://github.com/genkgo/xsl/files/1625541/filtre_xml_tei.txt)

**Comment by ossantr** [comment]
Do you know what could be the problem ? I'm using php 7.0.27 if it's useful.

**Comment by frederikbosch** [comment]
Haven't got the time to figure out. It is also quite a XSL file, which will not help. Are you able to reduce the problem to a more tiny one? That will save a lot of debugging.

**Comment by ossantr** [comment]
I reduce the xslt file and add some comments in english. I think the problem come from the part between lines 76 and 144, when I use the xsl:for-each-group.

[filtre_xml_tei.txt](https://github.com/genkgo/xsl/files/1639255/filtre_xml_tei.txt)

Thank you so much for your help!

**Comment by frederikbosch** [comment]
Please use the new alpha, maybe it works now.
