### ISSUE TITLE
getting null issue

### ISSUE THREAD

**Issue by niranjanpanem09** [genkgo/xsl#35]
we are getting null issue below, can you please help us in this

Genkgo\Xsl\Exception\TransformationException: Transformation failed: str_replace(): Argument #3 ($subject) must be of type array|string, null given in Genkgo\Xsl\XsltProcessor->catchLibXmlErrorThrowTransformException() (line 303 of C:\xampp new\htdocs\vendor\genkgo\xsl\src\XsltProcessor.php).

**Comment by frederikbosch** [comment]
Can you give me the full stack trace?

**Comment by niranjanpanem09** [comment]
Hi Frederik,

 

Below is the stack trace.

 

Genkgo\Xsl\Exception\TransformationException: Transformation failed: str_replace(): Argument #3 ($subject) must be of type array|string, null given in Genkgo\Xsl\XsltProcessor->catchLibXmlErrorThrowTransformException() (line 303 of C:\xampp new\htdocs\vendor\genkgo\xsl\src\XsltProcessor.php).

Genkgo\Xsl\XsltProcessor->createTranspiledDocument(Object) (Line: 166)

Genkgo\Xsl\XsltProcessor->getTranspiledStyleSheet(Object, Object) (Line: 81)

Genkgo\Xsl\XsltProcessor->Genkgo\Xsl\{closure}() (Line: 301)

Genkgo\Xsl\XsltProcessor->catchLibXmlErrorThrowTransformException(Object) (Line: 89)

Genkgo\Xsl\XsltProcessor->transformToXML(Object) (Line: 406)

Drupal\knowitall_cartridge\ThinCommonCartridgeXMLEncoder->encode(Array, 'tccxml', Array) (Line: 40)

Symfony\Component\Serializer\Encoder\ChainEncoder->encode(Array, 'tccxml', Array) (Line: 306)

Symfony\Component\Serializer\Serializer->encode(Array, 'tccxml', Array) (Line: 129)

Symfony\Component\Serializer\Serializer->serialize(Array, 'tccxml') (Line: 234)

Drupal\knowitall_cartridge\ThinCommonCartridgeGenerator->generateXml(Array) (Line: 137)

Drupal\knowitall_cartridge\Form\KnowitallCartridgeGenerateForm->submitForm(Array, Object)

call_user_func_array(Array, Array) (Line: 114)

Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)

Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 595)

Drupal\Core\Form\FormBuilder->processForm('knowitall_cartridge_ui_generate', Array, Object) (Line: 323)

Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)

Drupal\Core\Controller\FormController->getContentResult(Object, Object)

call_user_func_array(Array, Array) (Line: 123)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)

Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)

Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)

Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)

Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)

Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)

Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)

Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)

Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 718)

Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

 

 

 

 

Thanks,

Niranjan

**Comment by frederikbosch** [comment]
Okay. That exception contains a previous exception, can you provide [the stack trace](https://www.php.net/manual/en/throwable.gettraceasstring.php) of that [previous exception](https://www.php.net/manual/en/exception.getprevious.php).

**Comment by niranjanpanem09** [comment]
Hi Frederik,

 

We are getting this exception, we don’t have previous exception.

 

 

Thanks,

Niranjan

**Comment by frederikbosch** [comment]
There is a previous exception. On the referenced line, you can see that [a new exception is thrown with the other exception set as the previous one](https://github.com/genkgo/xsl/blob/master/src/XsltProcessor.php#L303).

If you cannot obtain the previous one, please show me a little bit of your xsl template.

**Comment by niranjanpanem09** [comment]
Hi Federik,

 

We got this below error, please help us.

 

The website encountered an unexpected error. Please try again later.
Error: Class "XSLTProcessor" not found in include() (line 14 of C:\xampp\htdocs\knowitall\vendor\genkgo\xsl\src\XsltProcessor.php).

include() (Line: 582)

Composer\Autoload\{closure}('C:\xampp\htdocs\knowitall\vendor\composer/../genkgo/xsl/src/XsltProcessor.php') (Line: 433)

Composer\Autoload\ClassLoader->loadClass('Genkgo\Xsl\XsltProcessor') (Line: 313)

Drupal\knowitall_cartridge\ThinCommonCartridgeXMLEncoder->encode(Array, 'tccxml', Array) (Line: 40)

Symfony\Component\Serializer\Encoder\ChainEncoder->encode(Array, 'tccxml', Array) (Line: 306)

Symfony\Component\Serializer\Serializer->encode(Array, 'tccxml', Array) (Line: 129)

Symfony\Component\Serializer\Serializer->serialize(Array, 'tccxml') (Line: 233)

Drupal\knowitall_cartridge\ThinCommonCartridgeGenerator->generateXml(Array) (Line: 137)

Drupal\knowitall_cartridge\Form\KnowitallCartridgeGenerateForm->submitForm(Array, Object)

call_user_func_array(Array, Array) (Line: 114)

Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)

Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 595)

Drupal\Core\Form\FormBuilder->processForm('knowitall_cartridge_ui_generate', Array, Object) (Line: 323)

Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)

Drupal\Core\Controller\FormController->getContentResult(Object, Object)

call_user_func_array(Array, Array) (Line: 123)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)

Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)

Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)

Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)

Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)

Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)

Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)

Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)

Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 713)

Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

 

 

Thanks,

Niranjan

**Comment by frederikbosch** [comment]
Sorry, but this is really going nowhere. Unless you provide me with a detailed analysis of what's going on, I am not going to waste my time here.

**Comment by niranjanpanem09** [comment]
Hi Federik,

 

Below is the xsl template.

 

  public function encode($data, $format, array $context = []) {

// dump ($data);

// die();

    $style = '<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0"

  xmlns="http://www.imsglobal.org/xsd/imsccv1p3/imscp_v1p1"

  xmlns:blti="http://www.imsglobal.org/xsd/imsbasiclti_v1p0"

  xmlns:csm="http://www.imsglobal.org/xsd/imsccv1p3/imscsmd_v1p0"

  xmlns:lomm="http://ltsc.ieee.org/xsd/imsccv1p3/LOM/manifest"

  xmlns:lomr="http://ltsc.ieee.org/xsd/imsccv1p3/LOM/resource"

  xmlns:lticc="http://www.imsglobal.org/xsd/imslticc_v1p3"

  xmlns:lticp="http://www.imsglobal.org/xsd/imslticp_v1p0"

  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <xsl:output method="xml" encoding="UTF-8" cdata-section-elements="description" omit-xml-declaratin="no" media-type="application/xml"/>

 

  <xsl:template match="/response">

    <root xsi:schemaLocation="http://www.imsglobal.org/xsd/imsccv1p3/imscp_v1p1 http://www.imsglobal.org/profile/cc/ccv1p3/ccv1p3_imscp_v1p2_v1p0.xsd http://www.imsglobal.org/xsd/imsbasiclti_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imsbasiclti_v1p0p1.xsd http://www.imsglobal.org/xsd/imsccv1p3/imscsmd_v1p0 http://www.imsglobal.org/profile/cc/ccv1p3/ccv1p3_imscsmd_v1p0.xsd http://ltsc.ieee.org/xsd/imsccv1p3/LOM/manifest http://www.imsglobal.org/profile/cc/ccv1p3/LOM/ccv1p3_lommanifest_v1p0.xsd http://ltsc.ieee.org/xsd/imsccv1p3/LOM/resource http://www.imsglobal.org/profile/cc/ccv1p3/LOM/ccv1p3_lomresource_v1p0.xsd http://www.imsglobal.org/xsd/imslticc_v1p3 http://www.imsglobal.org/xsd/lti/ltiv1p3/imslticc_v1p3.xsd http://www.imsglobal.org/xsd/imslticp_v1p0 http://www.imsglobal.org/xsd/lti/ltiv1p0/imslticp_v1p0.xsd">

      <items>

        <xsl:apply-templates select="item" mode="item" />

      </items>

      <resources>

        <xsl:apply-templates select="item" mode="resource" />

      </resources>

    </root>

  </xsl:template>

 

  <xsl:template match="item" mode="item">

    <xsl:variable name="nid" select="nid" />

    <xsl:variable name="uuid" select="uuid" />

    <item identifier="ITEM_{$nid}" identifierref="RESOURCE_LTI_{$nid}">

      <title>

        <xsl:value-of select="title"/>

      </title>

    </item>

  </xsl:template>

 

  <xsl:template match="item" mode="resource">

    <xsl:variable name="nid" select="nid" />

    <xsl:variable name="uuid" select="uuid" />

    <resource identifier="RESOURCE_LTI_{$nid}" type="imsbasiclti_xmlv1p3">

      <metadata>

        <lomr:lom>

          <lomr:general>

            <lomr:identifier>

              <lomr:catalog>GUID</lomr:catalog>

              <lomr:entry><xsl:value-of select="uuid"/></lomr:entry>

            </lomr:identifier>

            <lomr:title>

              <lomr:string language="en-US"><xsl:value-of select="title"/></lomr:string>

            </lomr:title>

            <lomr:description>

              <lomr:string language="en-US"><xsl:value-of select="description"/></lomr:string>

            </lomr:description>

            <xsl:if test="count(subjects/subject) > 0 or count(tags/tag) > 0">

              <lomr:keyword>

                <xsl:apply-templates select="subjects" />

                <xsl:apply-templates select="tags" />

              </lomr:keyword>

            </xsl:if>

            <lomr:language>en-us</lomr:language>

          </lomr:general>

          <lomr:lifeCycle>

            <lomr:contribute>

              <lomr:role>

                <lomr:value><xsl:value-of select="contribute/role"/></lomr:value>

              </lomr:role>

              <lomr:entity><xsl:value-of select="contribute/entity"/></lomr:entity>

              <lomr:date>

                <lomr:dateTime><xsl:value-of select="contribute/date"/></lomr:dateTime>

              </lomr:date>

            </lomr:contribute>

          </lomr:lifeCycle>

          <lomr:rights>

            <lomr:description>

              <lomr:string language="en-US">South Carolina ETV Commission</lomr:string>

            </lomr:description>

          </lomr:rights>

          <lomr:educational>

            <lomr:typicalAgeRange>

              <lomr:string><xsl:value-of select="grade_levels/range"/></lomr:string>

            </lomr:typicalAgeRange>

            <lomr:learningResourceType>

              <lomr:value><xsl:value-of select="resource_type"/></lomr:value>

            </lomr:learningResourceType>

            <lomr:intendedEndUserRole>

              <lomr:source><xsl:value-of select="intended_end_user_role/source"/></lomr:source>

              <lomr:value><xsl:value-of select="intended_end_user_role/value"/></lomr:value>

            </lomr:intendedEndUserRole>

          </lomr:educational>

        </lomr:lom>

        <csm:curriculumStandardsMetadataSet>

          <csm:curriculumStandardsMetadata providerId="AB">

            <xsl:apply-templates select="standards" />

          </csm:curriculumStandardsMetadata>

        </csm:curriculumStandardsMetadataSet>

      </metadata>

    </resource>

  </xsl:template>

 

  <xsl:template match="standards">

    <xsl:for-each-group select="standard" group-by="state">

      <csm:setOfGUIDs region="{current-grouping-key()}" version="1.0">

        <xsl:for-each select="current-group()">

          <csm:labelledGUID>

            <csm:label><xsl:value-of select="standard"/></csm:label>

            <csm:GUID><xsl:value-of select="guid"/></csm:GUID>

          </csm:labelledGUID>

          <xsl:text>

          </xsl:text>

        </xsl:for-each>

      </csm:setOfGUIDs>

    </xsl:for-each-group>

  </xsl:template>

 

  <xsl:template match="subjects">

    <xsl:apply-templates select="subject" />

  </xsl:template>

 

  <xsl:template match="subjects/subject">

    <lomr:string language="en-US"><xsl:value-of select="."/></lomr:string>

  </xsl:template>

 

  <xsl:template match="tags">

    <xsl:apply-templates select="tag" />

  </xsl:template>

 

  <xsl:template match="tags/tag">

    <lomr:string language="en-US"><xsl:value-of select="."/></lomr:string>

  </xsl:template>

 

</xsl:stylesheet>';

 

    $xslt = new XSLTProcessor();

    $xslt->importStylesheet(new SimpleXMLElement($style));

    // dump ($context);

    // die();

    $parent = parent::encode($data, 'xml', $context);

    return $xslt->transformToXml(new SimpleXMLElement($parent));

  }

 

 

Thanks,

Niranjan

**Comment by frederikbosch** [comment]
I think it is related to the fact you are using it on Windows. Have [a look here](https://github.com/genkgo/xsl/blob/master/src/XsltProcessor.php#L228). 

Replace 
`$documentURI = \str_replace('file:', '/', $documentURI);` 

with 
`$documentURI = \str_replace('file:', '/', (string)$documentURI);`

Does that solve your issue?

**Comment by niranjanpanem09** [comment]
Hi Genkgo,

 

We got this below exception, when we are trying to fetch previous exception, please help us in this.

 

The website encountered an unexpected error. Please try again later.

TypeError: Symfony\Component\Serializer\Serializer::serialize(): Return value must be of type string, null returned in Symfony\Component\Serializer\Serializer->serialize() (line 129 of C:\wamp64\www\www.knowitall.org\vendor\symfony\serializer\Serializer.php).

Symfony\Component\Serializer\Serializer->serialize(Array, 'tccxml') (Line: 233)

Drupal\knowitall_cartridge\ThinCommonCartridgeGenerator->generateXml(Array) (Line: 137)

Drupal\knowitall_cartridge\Form\KnowitallCartridgeGenerateForm->submitForm(Array, Object)

call_user_func_array(Array, Array) (Line: 114)

Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)

Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 595)

Drupal\Core\Form\FormBuilder->processForm('knowitall_cartridge_ui_generate', Array, Object) (Line: 323)

Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)

Drupal\Core\Controller\FormController->getContentResult(Object, Object)

call_user_func_array(Array, Array) (Line: 123)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 580)

Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)

Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 169)

Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 81)

Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)

Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)

Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)

Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)

Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)

Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)

Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 713)

Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

 

 

 

Thanks,

Niranjan
